package proyectoticoeats;

import capaDatos.UsuarioD;
import capaLogica.Usuario;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Vellaquito
 */
public class frmInicio extends javax.swing.JFrame {

    private int cantClaveError;

    public frmInicio() {
        initComponents();
        getContentPane().requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCorreoElectronico = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        lblToBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TicoEats");
        setMaximumSize(new java.awt.Dimension(300, 347));
        setPreferredSize(new java.awt.Dimension(300, 385));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCorreoElectronico.setForeground(new java.awt.Color(153, 153, 153));
        txtCorreoElectronico.setText("example@email.com");
        txtCorreoElectronico.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCorreoElectronicoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoElectronicoFocusLost(evt);
            }
        });
        getContentPane().add(txtCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 190, -1));

        lblCorreo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCorreo.setText("Correo Electronico");
        getContentPane().add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        lblPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPassword.setText("Contrasena");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        btnIngresar.setBackground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 100, -1));

        btnRegistro.setBackground(new java.awt.Color(20, 183, 110));
        btnRegistro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRegistro.setText("REGISTRARSE");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        txtPassword.setForeground(new java.awt.Color(153, 153, 153));
        txtPassword.setText("passwordreset");
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 190, -1));

        lblToBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/login2.png"))); // NOI18N
        lblToBackground.setText("jLabel1");
        lblToBackground.setMaximumSize(new java.awt.Dimension(538, 560));
        lblToBackground.setMinimumSize(new java.awt.Dimension(538, 560));
        lblToBackground.setPreferredSize(new java.awt.Dimension(538, 560));
        getContentPane().add(lblToBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 347));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoElectronicoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoElectronicoFocusGained
        if (txtCorreoElectronico.getText().equals("example@email.com")) {
            txtCorreoElectronico.setText("");
            txtCorreoElectronico.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txtCorreoElectronicoFocusGained

    private void txtCorreoElectronicoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoElectronicoFocusLost
        if (txtCorreoElectronico.getText().equals("")) {
            txtCorreoElectronico.setText("example@email.com");
            txtCorreoElectronico.setForeground(new Color(153, 152, 153));
        }
    }//GEN-LAST:event_txtCorreoElectronicoFocusLost

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        if (!validarDatos()) {
            return;
        }
        else{
            Usuario objUsuario = new UsuarioD().ConsultaUsuario(txtCorreoElectronico.getText(), txtPassword.getText(), 0);
            frmMenu ventana = new frmMenu(objUsuario);
            ventana.setVisible(true);
            ventana.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_btnIngresarActionPerformed
    private Boolean validarDatos(){
    if (txtCorreoElectronico.getText().equals("") || txtCorreoElectronico.getText().equals("example@email.com")) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el correo electrónico");
            txtCorreoElectronico.requestFocus();
            return false;
        }
        if (!txtCorreoElectronico.getText().matches("^[A-Za-z0-9_.]+[@][A-Za-z.]+$") && !txtCorreoElectronico.getText().toLowerCase().equals("admin")) {
            JOptionPane.showMessageDialog(this, "El correo electrónico no tiene el formato correcto");
            txtCorreoElectronico.requestFocus();
            return false;
        }
        if (!new UsuarioD().ExisteUsuario(txtCorreoElectronico.getText())) {
            JOptionPane.showMessageDialog(this, "El correo electrónico no se encuentra registrado");
            txtCorreoElectronico.requestFocus();
            return false;
        }
        if (txtPassword.getText().equals("") || txtPassword.getText().equals("passwordreset")) {
            JOptionPane.showMessageDialog(this, "Debe ingresar la contraseña");
            txtPassword.requestFocus();
            return false;
        }
        Usuario objUsuario = new UsuarioD().ConsultaUsuario(txtCorreoElectronico.getText(), "", 1);
        if(objUsuario.getESTADO().equals("INACTIVO")){
           JOptionPane.showMessageDialog(this, "El correo ingresado se encuentra inactivo");
           return false;
        }
        
        if (!objUsuario.getCONTRASENNA().equals(txtPassword.getText())) {
            if (!txtCorreoElectronico.getText().toLowerCase().equals("admin")) {
                cantClaveError++;
            }
            if(cantClaveError<3){
            JOptionPane.showMessageDialog(this, "Contraseña incorrecta");
            txtPassword.requestFocus();
            }
            if (cantClaveError==3) {
                JOptionPane.showMessageDialog(this, "La cuenta "+txtCorreoElectronico.getText()+" se desactivo por seguridad, consulte con administración");
                 new UsuarioD().ActualizarEstadoUsuario(txtCorreoElectronico.getText(), 0);
                 System.exit(1);
            }
            return false;
        }
        return true;
    }
    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        if (txtPassword.getText().equals("passwordreset")) {
            txtPassword.setText("");
            txtPassword.setForeground(new Color(0, 0, 0));
        }     // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordFocusGained

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        frmRegistro ventana = new frmRegistro();
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblToBackground;
    private javax.swing.JTextField txtCorreoElectronico;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
