package proyectoticoeats;

import capaDatos.UsuarioD;
import capaLogica.PaisOrigen;
import capaLogica.Tarjeta;
import capaLogica.TipoTarjeta;
import capaLogica.TipoUsuario;
import capaLogica.Usuario;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Francisco Arce Chavarria <danielarcesoftware@gmail.com>
 */
public class frmRegistro extends javax.swing.JFrame {

    /**
     * Creates new form frmRegistro
     */
    public frmRegistro() {
        initComponents();
        getContentPane().requestFocus();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupUser = new javax.swing.ButtonGroup();
        btnGroupCard = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblImgUser = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNumeroTarjeta = new javax.swing.JTextField();
        lblPais = new javax.swing.JLabel();
        cboPais = new javax.swing.JComboBox<>();
        rdbTipoUsuarioGerente = new javax.swing.JRadioButton();
        lblPerfil = new javax.swing.JLabel();
        rdbTipoUsuarioRegular = new javax.swing.JRadioButton();
        lblPerfil1 = new javax.swing.JLabel();
        rdbTipoTarjetaVisa = new javax.swing.JRadioButton();
        rdbTipoTarjetaMaster = new javax.swing.JRadioButton();
        lblNumeroTarjeta = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblVence = new javax.swing.JLabel();
        cboMes = new javax.swing.JComboBox<>();
        cboYear = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblCodigo = new javax.swing.JLabel();
        txtCodigoTarjeta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImgUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/userIcon.png"))); // NOI18N
        jPanel1.add(lblImgUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 10, 70, -1));

        lblNombre.setText("Nombre");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        txtNumeroTarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroTarjetaKeyTyped(evt);
            }
        });
        jPanel1.add(txtNumeroTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 180, -1));

        lblPais.setText("Pais");
        jPanel1.add(lblPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));
        jPanel1.add(cboPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 246, -1));

        btnGroupUser.add(rdbTipoUsuarioGerente);
        rdbTipoUsuarioGerente.setText("Gerente");
        jPanel1.add(rdbTipoUsuarioGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        lblPerfil.setText("Tipo Perfil");
        jPanel1.add(lblPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        btnGroupUser.add(rdbTipoUsuarioRegular);
        rdbTipoUsuarioRegular.setSelected(true);
        rdbTipoUsuarioRegular.setText("Regular");
        jPanel1.add(rdbTipoUsuarioRegular, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        lblPerfil1.setText("Tipo Tarjeta");
        jPanel1.add(lblPerfil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        btnGroupCard.add(rdbTipoTarjetaVisa);
        rdbTipoTarjetaVisa.setSelected(true);
        rdbTipoTarjetaVisa.setText("Visa");
        jPanel1.add(rdbTipoTarjetaVisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        btnGroupCard.add(rdbTipoTarjetaMaster);
        rdbTipoTarjetaMaster.setText("Master Card");
        jPanel1.add(rdbTipoTarjetaMaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        lblNumeroTarjeta.setText("Número Tarjeta");
        jPanel1.add(lblNumeroTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 246, -1));

        lblVence.setText("Fecha Vencimiento");
        jPanel1.add(lblVence, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        cboMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre", " " }));
        jPanel1.add(cboMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 110, -1));

        cboYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", " " }));
        jPanel1.add(cboYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 60, -1));

        btnRegistrar.setBackground(new java.awt.Color(20, 183, 110));
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 160, -1));

        btnRegresar.setBackground(new java.awt.Color(0, 0, 0));
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        lblEmail.setText("Correo Electrónico");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 246, -1));

        lblPassword.setText("Contraseña");
        jPanel1.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 246, -1));

        lblCodigo.setText("Código");
        jPanel1.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        txtCodigoTarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoTarjetaKeyTyped(evt);
            }
        });
        jPanel1.add(txtCodigoTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 55, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if (!validarDatos()) {
            return;
        } else {
            Tarjeta objTarjeta = new Tarjeta(TipoTarjeta.Visa, txtNumeroTarjeta.getText(), txtCodigoTarjeta.getText(), cboMes.getSelectedItem().toString() + "/" + cboYear.getSelectedItem().toString());
            Usuario objUsuario = new Usuario(txtEmail.getText(), txtNombre.getText(), txtPassword.getText(), PaisOrigen.COSTA_RICA, TipoUsuario.Regular, objTarjeta);
            
            new UsuarioD().MantenimientoUsuario(objUsuario, 0);
            JOptionPane.showMessageDialog(this, "Se registro correctamente, ingrese al sistema con sus datos");
            this.dispose();
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed
    //Valida todos los datos para registrar al usuario
    private Boolean validarDatos() {
        if (!isNotNullNotEmpty(txtEmail.getText())) {
            JOptionPane.showMessageDialog(this, "Ingrese el correo electrónico");
            txtEmail.requestFocus();
            return false;
        }
        if (!txtEmail.getText().matches("^[A-Za-z0-9_.]+[@][A-Za-z.]+$")) {
            JOptionPane.showMessageDialog(this, "El correo electrónico no tiene el formato correcto");
            txtEmail.requestFocus();
            return false;
        }
        if (new UsuarioD().ExisteUsuario(txtEmail.getText())) {
            JOptionPane.showMessageDialog(this, "El correo electrónico ya se encuentra en uso por otro usuario");
            txtEmail.requestFocus();
            return false;
        }
        if (!isNotNullNotEmpty(txtNombre.getText())) {
            JOptionPane.showMessageDialog(this, "Ingrese el nombre");
            txtNombre.requestFocus();
            return false;
        }
        if (!isNotNullNotEmpty(txtPassword.getText())) {
            JOptionPane.showMessageDialog(this, "Ingrese la contraseña para asignar a su usuario");
            txtPassword.requestFocus();
            return false;
        }
        if (!isNotNullNotEmpty(txtPassword.getText())) {
            JOptionPane.showMessageDialog(this, "Ingrese la contraseña para asignar a su usuario");
            txtPassword.requestFocus();
            return false;
        }
        if (cboPais.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione el país");
            cboPais.requestFocus();
            return false;
        }
        if (!isNotNullNotEmpty(txtNumeroTarjeta.getText())) {
            JOptionPane.showMessageDialog(this, "Ingrese el número de tarjeta");
            txtNumeroTarjeta.requestFocus();
            return false;
        }
        if (!formulaLuhn(txtNumeroTarjeta.getText())) {
            JOptionPane.showMessageDialog(this, "La tarjeta ingresada no tiene un formato correcto");
            txtNumeroTarjeta.requestFocus();
            return false;
        }
        int tipoTarjeta = rdbTipoTarjetaVisa.isSelected() ? Integer.parseInt(txtNumeroTarjeta.getText().substring(0, 4)) : Integer.parseInt(txtNumeroTarjeta.getText().substring(0, 3));

        if (rdbTipoTarjetaVisa.isSelected() && !(tipoTarjeta >= 4000 && tipoTarjeta <= 4999)) {
            JOptionPane.showMessageDialog(this, "La tarjeta ingresada no tiene un formato de tarjeta de tipo VISA");
            txtNumeroTarjeta.requestFocus();
            return false;
        }

        if (rdbTipoTarjetaMaster.isSelected() && !(tipoTarjeta >= 510 && tipoTarjeta <= 559)) {
            JOptionPane.showMessageDialog(this, "La tarjeta ingresada no tiene un formato de tarjeta de tipo MASTER CARD");
            txtNumeroTarjeta.requestFocus();
            return false;
        }

        if (!isNotNullNotEmpty(txtCodigoTarjeta.getText())) {
            JOptionPane.showMessageDialog(this, "Ingrese el código de la tarjeta");
            txtCodigoTarjeta.requestFocus();
            return false;
        }
        if (txtCodigoTarjeta.getText().length() != 4) {
            JOptionPane.showMessageDialog(this, "El código de la tarjeta debe de ser de 4 dígitos");
            txtCodigoTarjeta.requestFocus();
            return false;
        }
        if (cboYear.getSelectedItem() == "2021" && (cboMes.getSelectedItem().equals("Enero") || cboMes.getSelectedItem().equals("Febrero")|| cboMes.getSelectedItem().equals("Marzo")|| cboMes.getSelectedItem().equals("Abril"))) {
            JOptionPane.showMessageDialog(this, "La tarjeta ingresada tiene una fecha expirada");
            txtCodigoTarjeta.requestFocus();
            return false;
        }
        return true;
    }

    //Se valida el tamaño de la tarjeta que sea maximo de 16 digitos
    private void txtNumeroTarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroTarjetaKeyTyped
        char c = evt.getKeyChar();
        if (txtNumeroTarjeta.getText().length() == 16) {
            evt.consume();
        }
        if (!(Character.isDigit(c))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNumeroTarjetaKeyTyped

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    //Se valida el tamaño de codigo que sea maximo de 4 digitos
    private void txtCodigoTarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoTarjetaKeyTyped
        char c = evt.getKeyChar();
        if (txtCodigoTarjeta.getText().length() == 4) {
            evt.consume();
        }
        if (!(Character.isDigit(c))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCodigoTarjetaKeyTyped

    //Se regresa a la pantalla de inicio cuando se cierra la pantalla de registro
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        frmInicio ventana = new frmInicio();
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowClosed

    //Carga de datos requeridos
    private void cargarDatos() {
        cargarPais();
    }

    //Se carga el combo box de paises
    private void cargarPais() {
        for (PaisOrigen pais : PaisOrigen.values()) {
            cboPais.addItem(pais.getNombre());
        }
        cboPais.setSelectedIndex(-1);
    }

    //Metodo para validar nulos o vacios
    public static boolean isNotNullNotEmpty(
            final String string) {
        return string != null && !string.isEmpty() && !string.trim().isEmpty();
    }

    //FormulaLuhn para validar si la tarjeta ingresa es correcta
    private static boolean formulaLuhn(String numero) {

        int s1 = 0, s2 = 0;
        String reversa = new StringBuffer(numero).reverse().toString();
        for (int i = 0; i < reversa.length(); i++) {
            int digito = Character.digit(reversa.charAt(i), 10);
            if (i % 2 == 0) {
                s1 += digito;
            } else {
                s2 += 2 * digito;
                if (digito >= 5) {
                    s2 -= 9;
                }
            }
        }
        return (s1 + s2) % 10 == 0;

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupCard;
    private javax.swing.ButtonGroup btnGroupUser;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cboMes;
    private javax.swing.JComboBox<String> cboPais;
    private javax.swing.JComboBox<String> cboYear;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblImgUser;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumeroTarjeta;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JLabel lblPerfil1;
    private javax.swing.JLabel lblVence;
    private javax.swing.JRadioButton rdbTipoTarjetaMaster;
    private javax.swing.JRadioButton rdbTipoTarjetaVisa;
    private javax.swing.JRadioButton rdbTipoUsuarioGerente;
    private javax.swing.JRadioButton rdbTipoUsuarioRegular;
    private javax.swing.JTextField txtCodigoTarjeta;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroTarjeta;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
