package proyectoticoeats;

import capaDatos.OrdenD;
import capaDatos.ProductoD;
import capaDatos.RestauranteD;
import capaLogica.Orden;
import capaLogica.Producto;
import capaLogica.Restaurante;
import capaLogica.Usuario;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Francisco Arce Chavarria <danielarcesoftware@gmail.com>
 */
public class frmReportes extends javax.swing.JFrame {

    Usuario user = new Usuario();
    DefaultTableModel tblModelReporte = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            //all cells false
            return false;
        }
    };

    public frmReportes(Usuario user) {
        initComponents();
        getContentPane().requestFocus();
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        lblImagenUser = new javax.swing.JLabel();
        lblPerfil = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cboTipoReporte = new javax.swing.JComboBox<>();
        lblReporte = new javax.swing.JLabel();
        btnBuscarReporte = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReporte = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reportes");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(20, 183, 110));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagenUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user.png"))); // NOI18N
        jPanel12.add(lblImagenUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, -1));

        lblPerfil.setText("Daniel Arce Chavarria / ADMINISTRADOR");
        lblPerfil.setToolTipText("");
        jPanel12.add(lblPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 13, 330, 10));

        cboTipoReporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos los Productos", "Los Tres Mejores Restaurantes", "Compras Relizadas por restaurante" }));

        lblReporte.setText("Reporte");

        btnBuscarReporte.setText("Buscar");
        btnBuscarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboTipoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarReporte)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReporte)
                    .addComponent(cboTipoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        jScrollPane1.setViewportView(tblReporte);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        frmMenu ventana = new frmMenu(user);
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowClosed

    private void btnBuscarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarReporteActionPerformed
        limpiarTablaReporte();
        if (cboTipoReporte.getSelectedItem() == "Todos los Productos") {
            cargarReporteTodosLosProductos();
        } else if (cboTipoReporte.getSelectedItem() == "Los Tres Mejores Restaurantes") {
            cargarReporteLosTresMejoresRestaurantes();
        } else if (cboTipoReporte.getSelectedItem() == "Compras Relizadas por restaurante") {
            cargarReporteComprasRealizadasPorRestaurante();
        }else{
            tblReporte.setModel(tblModelReporte);
        }
    }//GEN-LAST:event_btnBuscarReporteActionPerformed

    private void cargarReporteTodosLosProductos() {
        tblModelReporte.addColumn("CODIGO");
        tblModelReporte.addColumn("DESCRIPCION");
        tblModelReporte.addColumn("RESTAURANTE");
        tblModelReporte.addColumn("TIPO RESTAURANTE");
        tblModelReporte.setRowCount(0);
        ArrayList<Restaurante> lstRestaurantes = new RestauranteD().ConsultaRestaurantes(0, "", "");
        for (Restaurante itemRestaurante : lstRestaurantes) {
            ArrayList<Producto> lstUsuarios = new ProductoD().ConsultaProductos(2, "", itemRestaurante.getNOMBRE());
            if (lstUsuarios != null) {
                for (Producto itemProducto : lstUsuarios) {
                    String[] fila = {itemProducto.getCODIGO(), itemProducto.getDESCRIPCION(), itemRestaurante.getNOMBRE(), itemRestaurante.getTIPO_COMIDA().name()};
                    tblModelReporte.addRow(fila);
                }
            }
            tblReporte.setModel(tblModelReporte);
        }
    }

    private void cargarReporteLosTresMejoresRestaurantes() {
        tblModelReporte.addColumn("RESTAURANTE");
        tblModelReporte.addColumn("TIPO RESTAURANTE");
        tblModelReporte.addColumn("CALIFICACION");
        
        tblModelReporte.setRowCount(0);
        ArrayList<Restaurante> lstRestaurantes = new RestauranteD().ConsultaRestaurantes(4, "", "");
        for (Restaurante itemRestaurante : lstRestaurantes) {
                    String[] fila = {itemRestaurante.getNOMBRE(), itemRestaurante.getTIPO_COMIDA().name(), itemRestaurante.getCALIFICACION()+"★"};
                    tblModelReporte.addRow(fila);
            tblReporte.setModel(tblModelReporte);
        }
    }

    private void cargarReporteComprasRealizadasPorRestaurante() {
        tblModelReporte.addColumn("ORDEN");
        tblModelReporte.addColumn("CLIENTE");
        tblModelReporte.addColumn("TOTAL");
        tblModelReporte.addColumn("FECHA CREACION");
        tblModelReporte.addColumn("TIEMPO PREPARACION");
        tblModelReporte.addColumn("CALIFICACION");
        tblModelReporte.addColumn("RESTAURANTE");
        tblModelReporte.setRowCount(0);
        ArrayList<Restaurante> lstRestaurantes = new RestauranteD().ConsultaRestaurantes(0, "", "");
        for (Restaurante itemRestaurante : lstRestaurantes) {
            ArrayList<Orden> lstOrden = new OrdenD().ConsultaOrdenes(2, "", itemRestaurante.getNOMBRE());
            if (lstOrden != null) {
                for (Orden itemOrden : lstOrden) {
                    String[] fila = {Integer.toString(itemOrden.getPK_ORDEN()), itemOrden.getCLIENTE(),Double.toString(itemOrden.getPRECIO_TOTAL()),itemOrden.getFECHA_CREACION(),Integer.toString(itemOrden.getTIEMPO_PREPARACION_TOTAL()),Integer.toString(itemOrden.getCALIFICACION()), itemRestaurante.getNOMBRE()};
                    tblModelReporte.addRow(fila);
                }
            }
            tblReporte.setModel(tblModelReporte);
        }
    }

    private void limpiarTablaReporte() {
        tblModelReporte = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReportes(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarReporte;
    private javax.swing.JComboBox<String> cboTipoReporte;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImagenUser;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JLabel lblReporte;
    private javax.swing.JTable tblReporte;
    // End of variables declaration//GEN-END:variables
}
