package proyectoticoeats;

import capaDatos.ProductoD;
import capaDatos.RestauranteD;
import capaLogica.Producto;
import capaLogica.Restaurante;
import capaLogica.Usuario;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Francisco Arce Chavarria <danielarcesoftware@gmail.com>
 */
public class frmTipoRestaurante extends javax.swing.JFrame {

    Usuario user = new Usuario();
    Boolean regresar_menu;
    ArrayList<Restaurante> lstRestaurante = new ArrayList<Restaurante>();

    public frmTipoRestaurante(Usuario user) {
        initComponents();
        getContentPane().requestFocus();
        this.user = user;
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnReposteria = new javax.swing.JButton();
        btnHamburguesas = new javax.swing.JButton();
        btnItaliano = new javax.swing.JButton();
        btnChino = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tipo Restaurante");
        setBackground(new java.awt.Color(20, 183, 110));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(20, 183, 110));

        btnReposteria.setBackground(new java.awt.Color(255, 255, 255));
        btnReposteria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/desayuno.png"))); // NOI18N
        btnReposteria.setText("Repostería");
        btnReposteria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReposteria.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnReposteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReposteriaActionPerformed(evt);
            }
        });

        btnHamburguesas.setBackground(new java.awt.Color(255, 255, 255));
        btnHamburguesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/hamburguesa.png"))); // NOI18N
        btnHamburguesas.setText("Hamburguesas");
        btnHamburguesas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHamburguesas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnHamburguesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHamburguesasActionPerformed(evt);
            }
        });

        btnItaliano.setBackground(new java.awt.Color(255, 255, 255));
        btnItaliano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pizza.png"))); // NOI18N
        btnItaliano.setText("Italiano");
        btnItaliano.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnItaliano.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnItaliano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItalianoActionPerformed(evt);
            }
        });

        btnChino.setBackground(new java.awt.Color(255, 255, 255));
        btnChino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ramen.png"))); // NOI18N
        btnChino.setText("Chino");
        btnChino.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnChino.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnChino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChinoActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setForeground(new java.awt.Color(0, 153, 51));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/exit.png"))); // NOI18N
        btnSalir.setText("Regresar");
        btnSalir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSalir.setIconTextGap(3);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReposteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHamburguesas, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnChino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnItaliano, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReposteria, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnItaliano, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChino, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHamburguesas, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (regresar_menu) {
            frmMenu ventana = new frmMenu(user);
            ventana.setVisible(true);
            ventana.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_formWindowClosed

    private void btnReposteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReposteriaActionPerformed
        abrirCarritoCompras("Reposteria");
    }//GEN-LAST:event_btnReposteriaActionPerformed

    private void btnItalianoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItalianoActionPerformed
        abrirCarritoCompras("Italiano");
    }//GEN-LAST:event_btnItalianoActionPerformed

    private void btnChinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChinoActionPerformed
        abrirCarritoCompras("Chino");
    }//GEN-LAST:event_btnChinoActionPerformed

    private void btnHamburguesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHamburguesasActionPerformed
        abrirCarritoCompras("Hamburguesas");
    }//GEN-LAST:event_btnHamburguesasActionPerformed
    private void cargarDatos(){
        lstRestaurante = new RestauranteD().ConsultaRestaurantes(0, "", "");
        validarDisponibilidad("Reposteria");
        validarDisponibilidad("Italiano");
        validarDisponibilidad("Chino");
        validarDisponibilidad("Hamburguesas");
        regresar_menu = true;
        JOptionPane.showMessageDialog(this, "Seleccione un tipo de restaurante");
    }
    private void validarDisponibilidad(String tipoRestaurante) {
        Boolean habilitar = false;
        if (lstRestaurante != null && lstRestaurante.size() > 0) {
            for (Restaurante restaurante : lstRestaurante) {
                if (tipoRestaurante.equals(restaurante.getTIPO_COMIDA().toString())) {
                    ArrayList<Producto> lstProductos = new ProductoD().ConsultaProductos(restaurante.equals("") ? 0 : 2, "", restaurante.getNOMBRE());
                    if (lstProductos != null && lstProductos.size() > 0) {
                        habilitar = true;
                    }
                }
            }
        }
        if (!habilitar) {
            deshabilitarTipoComida(tipoRestaurante);
        }
    }

    private void deshabilitarTipoComida(String tipoRestaurante) {
        switch (tipoRestaurante) {
            case "Reposteria":
                btnReposteria.setEnabled(false);
                break;
            case "Italiano":
                btnItaliano.setEnabled(false);
                break;
            case "Chino":
                btnChino.setEnabled(false);
                break;
            case "Hamburguesas":
                btnHamburguesas.setEnabled(false);
                break;
        }

    }

    private void abrirCarritoCompras(String tipoComida) {
        regresar_menu = false;
        frmRestaurante ventana = new frmRestaurante(user, tipoComida);
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(null);
        this.dispose();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTipoRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTipoRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTipoRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTipoRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTipoRestaurante(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChino;
    private javax.swing.JButton btnHamburguesas;
    private javax.swing.JButton btnItaliano;
    private javax.swing.JButton btnReposteria;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
